---
version: 3
vars:
  GO_TARGET_NAME: taskfile-lsp
  BUILD_DIR: "{{.ROOT_DIR}}/build"
  VSCODE_DIR: "{{.ROOT_DIR}}/vscode"
  VERSION: '{{.VERSION | default "latest" }}'
includes:
  go: ./taskfiles/go/Taskfile.yaml
  meson: ./taskfiles/meson/Taskfile.yaml
  vhs: ./taskfiles/vhs/Taskfile.yaml
  vscode: ./taskfiles/vscode/Taskfile.yaml
tasks:
  # Hello World
  build-dev: # This is a trailing comment
    aliases:
      - default
    cmds:
      - task: meson:build
      - task: go:build-dev

  # This is a comment
  build-release:
    aliases:
      - build
    cmds:
      - task: meson:build
        vars:
          BUILD_TYPE: release
          BUILD_ARGS: --clean
      - task: go:build-release
  build-tapes:
    silent: true
    aliases:
      - tapes
    cmds:
      - |
        for file in ./assets/[!_]*.tape; do
            [ -e "$file" ] || continue
            task vhs:tape VHS_FILE="$file"
        done

  test:
    cmds:
      - task: meson:test
      - task: go:test

  install:
    deps:
      - build-release
    cmds:
      - task: meson:install

  zip:
    cmds:
      - |
        ouch compress                   \
          assets                        \
          docker                        \
          internal                      \
          libtaskfile-parser            \
          taskfiles                     \
          wiki                          \
          .clang-format                 \
          .clang-tidy                   \
          .clangd                       \
          .dockerignore                 \
          .editorconfig                 \
          .env                          \
          .gitignore                    \
          .release-please-manifest.json \
          .rumdl.toml                   \
          .vale.ini                     \
          .valeignore                   \
          .yamlfmt                      \
          .yamllint                     \
          CHANGELOG.md                  \
          docker-compose.yaml           \
          go.mod                        \
          go.sum                        \
          lefthook.yml                  \
          LICENSE                       \
          main.go                       \
          meson.build                   \
          meson.format                  \
          meson.options                 \
          README.md                     \
          release-please-config.json    \
          Taskfile.yaml                 \
          VERSION                       \
          sources.zip

  clean:
    deps:
      - go:clean
      - meson:clean
      - vscode:clean
