---
name: Cleanup caches on Merged/Closed PRs
on:
  pull_request:
    types:
      - closed
jobs:
  cleanup-pr-caches:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clean
        uses: MyOriginal/cleanup-caches-action@v2
