---
name: Validate PR
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  lint-and-test-go:
    name: Lint and test Go sources
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed go files
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.go
      - name: go vet
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        run: |
          go vet \
            ./...
      - name: golangci-lint
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        run: |
          golangci-lint run ./...
      - name: go test
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        run: |
          go test \
            -v \
            -race \
            -covermode=atomic \
            ./...
  lint-dockerfiles:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed Dockerfiles
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*Dockerfile*
      - name: Lint changed Dockerfiles
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        run: |
          hadolint ${{ steps.changed.outputs.all_changed_files }}
  lint-yaml:
    name: Lint YAML files
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed YAML files
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.yml
            **/*.yaml
      - name: Lint yaml files
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        run: |
          yamllint ${{ steps.changed.outputs.all_changed_files }}
  lint-markdown-files:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed Markdown files
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.md
      - name: Lint using rumdl
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        run: |
          rumdl check ${{ steps.changed.outputs.all_changed_files }}
      - name: Lint using vale
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        run: |
          vale ${{ steps.changed.outputs.all_changed_files }}
  line-libtaskfile-parser-files:
    name: Lint and test libtaskfile-parser sources
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed C files
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          path: libtaskfile-parser
          safe_output: false
          files: |
            **/*.h
            **/*.c
            **/*.hpp
            **/*.cpp
            **/*.cc
      - name: Lint using clang-tidy
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        run: |
          clang-tidy -p build ${{ steps.changed.outputs.all_changed_files }}
      - name: Lint using iwyu
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        working-directory: libtaskfile-parser
        run: |
          include-what-you-use \
            -Xiwyu --no_fwd_decls \
            -Xiwyu --max_line_length=120 \
            -std=c23 \
            -Iinclude \
            -Isrc \
            ${{ steps.changed.outputs.all_changed_files }}
      - name: Test
        if: ${{ steps.changed.outputs.any_changed == 'true' }}
        run: |
          export CC=clang
          export CXX=clang++
          export LD=lld
          meson setup build
          meson compile -C build
          meson test -C build
# eslint:
#   glob: "*.{ts,js}"
#   root: "vscode"
#   run: pnpm lint
