---
name: Release task-lsp
on:
  push:
    branches:
      - main
  release:
    types:
      - published
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/build-env
permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write
  pages: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      go_release_created: ${{ steps.release.outputs['.--release_created'] }}
      go_tag: ${{ steps.release.outputs['.--tag_name'] }}
      go_version: ${{ steps.release.outputs['.--version'] }}

      docker_release_created: ${{ steps.release.outputs['docker/build-env--release_created'] }}
      docker_tag: ${{ steps.release.outputs['docker/build-env--tag_name'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: ${{ github.event_name == 'release' || needs.release-please.outputs.go_release_created == 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Toolchain (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            lld \
            meson \
            ninja-build
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Build libtaskfile-parser
        shell: bash
        run: |
          export CC=clang
          export CXX=clang++
          export LD=lld
          meson setup build
          meson compile -C build
      - name: Test libtaskfile-parser
        run: |
          meson test -C build
      - name: Test LSP
        run: |
          export CGO_ENABLED=1
          go test -v ./...
  release-lsp:
    needs:
      - release-please
      - test
    if: ${{ github.event_name == 'release' || needs.release-please.outputs.go_release_created == 'true' }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            os: linux
            arch: amd64
            target: linux-x64
            ext: ""
          - runner: macos-14
            os: darwin
            arch: arm64
            target: macos-arm64
            ext: ""
          - runner: macos-13
            os: darwin
            arch: amd64
            target: macos-x64
            ext: ""
          - runner: windows-latest
            os: windows
            arch: amd64
            target: win-x64
            ext: ".exe"
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Toolchain (Linux)
        if: matrix.runner == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            lld \
            meson \
            ninja-build
      - name: Install Toolchain (macOS)
        if: startsWith(matrix.runner, 'macos')
        run: |
          brew install \
            meson \
            ninja
      - name: Install Toolchain (Windows)
        if: matrix.runner == 'windows-latest'
        run: |
          pip install meson ninja
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Setup Nodejs & pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "12.3.4"
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'vscode/pnpm-lock.yaml'
      - name: Build libtaskfile-parser
        shell: bash
        run: |
          VERSION="${{ needs.release-please.outputs.go_version }}"
          if [ -z "$VERSION" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
          fi
          if [ "${{ matrix.runner }}" = "windows-latest" ]; then
            export CC=clang
            export CXX=clang++
          elif [ "${{ matrix.os }}" = "linux" ]; then
            export CC=clang
            export CXX=clang++
            export LD=lld
          fi
          meson setup build
          meson compile -C build
      - name: Build LSP
        shell: bash
        run: |
          export CGO_ENABLED=1
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          VERSION="${{ needs.release-please.outputs.go_version }}"
          if [ -z "$VERSION" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
          fi
          go build \
            -trimpath \
            -ldflags="-s -w -X taskfile-lsp/internal/lsp.Version=$VERSION" \
            -o taskfile-lsp-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} \
            .
      - name: Build VSCode Extension
        shell: bash
        run: |
          cd vscode
          pnpm install --frozen-lockfile
          npx @vscode/vsce package --target ${{ matrix.target }}
      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.go_tag || github.event.release.tag_name }}
          files: |
            taskfile-lsp-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
            vscode/*.vsix
  release-build-env:
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: ${{ github.event_name == 'release' || needs.release-please.outputs.docker_release_created == 'true' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clean tag version
        id: clean_version
        shell: bash
        run: |
          RAW_TAG="${{ needs.release-please.outputs.docker_tag || github.event.release.tag_name }}"
          CLEAN_TAG="${RAW_TAG#build-env-v}"
          echo "tag=$CLEAN_TAG" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Environment
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/build-env/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.clean_version.outputs.tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  publish-docs:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      contains(github.event.head_commit.message, 'chore(main): release docs')
    needs:
      - release-please
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'docs/pnpm-lock.yaml'
      - name: Install dependencies
        working-directory: ./docs
        run: pnpm install --frozen-lockfile
      - name: Build project
        working-directory: ./docs
        run: pnpm run build
      - name: Upload production artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
